export type zohoCaseData = {
  id: string;
  P_liza: string;
  Placa: string;
  Marca: string;
  Modelo: string;
  Punto_A: string;
  Punto_B: string;
  Operador: string;
  A_o: string;
  Chasis: string;
  Tiempo_estimado: string;
  Color: string;
  Solicitante: string;
  Plan: string;
  Description: string;
  Phone: string;
  Ubicaci_n: string;
  Suplidor: string;
  Status: string;
  Asistido_por: string;
  Product_Name: {};
};
